# original: https://raw.githubusercontent.com/crashdump/proto-tools/refs/heads/main/toml-plugins/atlas/plugin.toml

name = "atlas"
type = "cli"

[resolve]
versions = ["1.0.0"]
# https://github.com/ariga/atlas/releases

[platform.linux]
download-file = "atlas-community-linux-{arch}-v{version}"

[platform.macos]
download-file = "atlas-community-darwin-{arch}-v{version}"

[platform.windows]
download-file = "atlas-community-windows-{arch}-v{version}.exe"

[install]
download-url = "https://release.ariga.io/atlas/{download_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
