name = "beszel-agent"
type = "cli"

[resolve]
versions = ["0.18.2"]
# https://github.com/henrygd/beszel/releases

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install]
download-url = "https://github.com/henrygd/beszel/releases/download/{download_file}"

[platform.linux]
download-file = "v{version}/beszel-agent_linux_{arch}.tar.gz"

[platform.macos]
download-file = "v{version}/beszel-agent_darwin_{arch}.tar.gz"

[install.exes]
[install.exes.beszel-agent]
exe-path = "beszel-agent"
primary = true
