# original: https://raw.githubusercontent.com/appthrust/proto-toml-plugins/main/jq/plugin.toml

name = "jq"
type = "cli"

[resolve]
versions = ["1.8.1"]
# https://github.com/jqlang/jq/releases


[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"


[install]
download-url = "https://github.com/jqlang/jq/releases/download/{download_file}"

[platform.linux]
download-file = "jq-{version}/jq-linux-{arch}"
checksum-file = "jq-{version}/sha256sum.txt"

[platform.macos]
download-file = "jq-{version}/jq-macos-{arch}"
checksum-file = "jq-{version}/sha256sum.txt"
